services:
  - type: web
    name: amrthabo
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn amr_project.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_iDK37xeTRJnl@ep-rapid-mouse-adubprv1-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
